server:
  port: 7064
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: customer-service
  datasource:
    url: jdbc:h2:mem:customerdb
  boot:
    admin:
      client:
        url:
        - http://localhost:7000
management:
  endpoints:
    web:
      exposure:
        include: '*'
