server:
  port: 7060
spring:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: user-server
  datasource:
    url: jdbc:h2:mem:userdb
