logging:
  level:
    org:
      springframework:
        cloud:
          netflix:
            zuul: trace
            
server:
  port: 9000

spring:
  application:
    name: zuul-service

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    product-service:
      path: /product/**
      service-id: product-service
    order-service:
      path: /order/**
      service-id: order-service